package:
  name: conda-docs-deps
  version: 3.0

requirements:
  run:
    - python
    - perl
    - sphinx
    - numpydoc
    - continuum-sphinx-theme
    - help2man
    - man2html
    - futures # [py2k]
    - groff

test:
  commands:
    # Just to make sure it installs
    - echo
